/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服务健康检查
         * @description 返回服务运行状态及各依赖连通性检查结果。
         *     当前各依赖检查均为 stub（skipped），待后续迭代接入真实探针。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/jd-routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * JD 路由分析（stub）
         * @description 接收 JD 文本，触发 LangGraph 编排工作流（当前为 stub 实现，返回示例数据）。
         */
        post: operations["jd_routing_api_v1_agent_jd_routing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/interview/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 开始面试会话（stub） */
        post: operations["interview_start_api_v1_agent_interview_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/interview/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 继续面试会话（stub） */
        post: operations["interview_resume_api_v1_agent_interview_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/interview/{thread_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询面试会话状态（stub） */
        get: operations["interview_status_api_v1_agent_interview__thread_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出所有已注册 Skill
         * @description 返回当前进程中所有已通过 register_all_skills() 注册的 Skill 元信息。
         */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{name}/dispatch-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 检查指定 Skill 是否会被触发
         * @description 给定 JDContext 片段，调用指定 Skill 的 should_invoke() 并返回结果。用于验证路由规则是否符合预期，不会真正执行 Skill。
         */
        post: operations["dispatch_check_api_v1_skills__name__dispatch_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{name}/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 直接调用指定 Skill
         * @description 直接触发某个 Skill 执行，绕过 LangGraph 流程。用于人工调试和验收测试，返回 SkillOutput 原始 JSON。
         */
        post: operations["invoke_skill_api_v1_skills__name__invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DispatchCheckRequest
         * @description dispatch-check 端点的请求体，携带足够的 JDContext 字段用于路由判断。
         */
        DispatchCheckRequest: {
            /**
             * Jd Text
             * @default 示例 JD 文本
             */
            jd_text: string;
            /**
             * User Id
             * @default debug_user
             */
            user_id: string;
            /**
             * Request Id
             * @default debug_req
             */
            request_id: string;
            /**
             * @default {
             *       "preferred_lang": "zh"
             *     }
             */
            user_context: components["schemas"]["UserContext"];
            classification?: components["schemas"]["JDClassification"] | null;
        };
        /** DispatchCheckResponse */
        DispatchCheckResponse: {
            /** Skill Name */
            skill_name: string;
            /** Should Invoke */
            should_invoke: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewQuestion */
        InterviewQuestion: {
            /** Question */
            question: string;
            /** Intent */
            intent: string;
            /** Answer Points */
            answer_points: string[];
        };
        /** InterviewReport */
        InterviewReport: {
            /** Stage Scores */
            stage_scores: components["schemas"]["StageScore"][];
            /** Highlights */
            highlights: string[];
            /** Improvements */
            improvements: string[];
            /** Transcript Summary */
            transcript_summary: string;
        };
        /** InterviewResumeRequest */
        InterviewResumeRequest: {
            /** Thread Id */
            thread_id: string;
            /** User Input */
            user_input: string;
        };
        /** InterviewResumeResponse */
        InterviewResumeResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "waiting_user_input" | "completed" | "error";
            next_action?: components["schemas"]["NextAction"] | null;
            report?: components["schemas"]["InterviewReport"] | null;
        };
        /** InterviewStartRequest */
        InterviewStartRequest: {
            /** Thread Id */
            thread_id: string;
            /** User Id */
            user_id: string;
            /** Company */
            company: string;
            /** Position */
            position: string;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
        };
        /** InterviewStartResponse */
        InterviewStartResponse: {
            /** Thread Id */
            thread_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "waiting_user_input" | "completed" | "error";
            next_action?: components["schemas"]["NextAction"] | null;
        };
        /** InterviewStatusResponse */
        InterviewStatusResponse: {
            /** Thread Id */
            thread_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "waiting_user_input" | "completed" | "not_found";
            /** Current Stage */
            current_stage?: string | null;
            /** Last Checkpoint At */
            last_checkpoint_at?: string | null;
            /**
             * Transcript Length
             * @default 0
             */
            transcript_length: number;
        };
        /**
         * InvokeRequest
         * @description invoke 端点的请求体。
         */
        InvokeRequest: {
            /** Jd Text */
            jd_text: string;
            /**
             * User Id
             * @default debug_user
             */
            user_id: string;
            /**
             * Request Id
             * @default debug_req
             */
            request_id: string;
            /**
             * @default {
             *       "preferred_lang": "zh"
             *     }
             */
            user_context: components["schemas"]["UserContext"];
            classification?: components["schemas"]["JDClassification"] | null;
            /**
             * Timeout Seconds
             * @default 15
             */
            timeout_seconds: number;
        };
        /** JDClassification */
        JDClassification: {
            /**
             * Job Type
             * @enum {string}
             */
            job_type: "tech" | "product" | "design" | "ops" | "mgmt";
            /** Sub Type */
            sub_type: string;
            /**
             * Level
             * @enum {string}
             */
            level: "junior" | "middle" | "senior" | "lead";
            /**
             * Locale
             * @enum {string}
             */
            locale: "zh" | "en";
            /**
             * Channel
             * @enum {string}
             */
            channel: "social" | "campus";
        };
        /** JDRoutingRequest */
        JDRoutingRequest: {
            /** Request Id */
            request_id: string;
            /** User Id */
            user_id: string;
            /** Jd Text */
            jd_text: string;
            user_context?: components["schemas"]["UserContext"];
        };
        /** JDRoutingResponse */
        JDRoutingResponse: {
            /** Request Id */
            request_id: string;
            classification: components["schemas"]["JDClassification"];
            /** Invoked Skills */
            invoked_skills: string[];
            /** Skipped Skills */
            skipped_skills: string[];
            results: components["schemas"]["JDRoutingResults"];
            metadata: components["schemas"]["ResponseMetadata"];
        };
        /** JDRoutingResults */
        JDRoutingResults: {
            /** Jd Summary */
            jd_summary: string;
            /** Resume Advice */
            resume_advice?: components["schemas"]["ResumeAdviceItem"][];
            /** Interview Questions */
            interview_questions?: components["schemas"]["InterviewQuestion"][];
        };
        /** NextAction */
        NextAction: {
            /**
             * Type
             * @enum {string}
             */
            type: "ask_question" | "wait" | "end";
            /** Content */
            content: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "intro" | "project_deep_dive" | "tech_qa" | "scenario" | "reverse" | "closing";
        };
        /** ResponseMetadata */
        ResponseMetadata: {
            /** Latency Ms */
            latency_ms: number;
            /** Tokens Used */
            tokens_used?: number | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** ResumeAdviceItem */
        ResumeAdviceItem: {
            /**
             * Priority
             * @enum {string}
             */
            priority: "high" | "medium" | "low";
            /** Advice */
            advice: string;
            /** Related Jd Requirement */
            related_jd_requirement?: string | null;
        };
        /** SkillInfo */
        SkillInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Description */
            description: string;
            /** When To Use */
            when_to_use: string;
            /** When Not To Use */
            when_not_to_use: string;
            /** Tags */
            tags: string[];
            /** Dependencies */
            dependencies: string[];
        };
        /** SkillListResponse */
        SkillListResponse: {
            /** Count */
            count: number;
            /** Skills */
            skills: components["schemas"]["SkillInfo"][];
        };
        /** StageScore */
        StageScore: {
            /** Stage */
            stage: string;
            /** Score */
            score: number;
            /** Comment */
            comment: string;
        };
        /** UserContext */
        UserContext: {
            /** User Kb Id */
            user_kb_id?: string | null;
            /**
             * Preferred Lang
             * @default zh
             * @enum {string}
             */
            preferred_lang: "zh" | "en";
            /** Github Username */
            github_username?: string | null;
            /** Portfolio Doc Ref */
            portfolio_doc_ref?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    jd_routing_api_v1_agent_jd_routing_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JDRoutingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JDRoutingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_start_api_v1_agent_interview_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_resume_api_v1_agent_interview_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_status_api_v1_agent_interview__thread_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
        };
    };
    dispatch_check_api_v1_skills__name__dispatch_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoke_skill_api_v1_skills__name__invoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
